cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/3rdparty/ittnotify/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/3rdparty/carotene/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/3rdparty/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/3rdparty/quirc/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/3rdparty/openvx/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/ml/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/ts/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/imgproc/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/dnn/src/vkcom/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/dnn/src/ocl4dnn/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/dnn/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/videoio/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/objdetect/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/world/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/core/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/flann/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/photo/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/calib3d/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/imgcodecs/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/stitching/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/highgui/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/gapi/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/features2d/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/modules/video/include .
cp -r /disk2/OpenCvDev/opencv/opencv-4.0.0/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/build/3rdparty/ade/ade-0.1.1d/sources/ade/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/build/3rdparty/ippicv/ippicv_lnx/icv/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/build/3rdparty/ippicv/ippicv_lnx/iw/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/build/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/aruco/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/superres/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/xfeatures2d/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/ximgproc/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/cudalegacy/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/shape/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/cudastereo/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/structured_light/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/optflow/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/cudawarping/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/text/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/cudaoptflow/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/cudev/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/sfm/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/reg/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/bgsegm/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/freetype/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/datasets/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/fuzzy/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/matlab/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/videostab/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/surface_matching/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/xphoto/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/cnn_3dobj/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/phase_unwrapping/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/stereo/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/tracking/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/xobjdetect/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/ccalib/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/hfs/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/cudabgsegm/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/dnn_objdetect/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/bioinspired/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/cudaimgproc/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/ovis/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/cudafilters/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/cudacodec/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/img_hash/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/cudaobjdetect/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/line_descriptor/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/dpm/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/plot/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/saliency/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/rgbd/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/viz/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/cudafeatures2d/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/cvv/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/cudaarithm/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/face/include .
cp -r /disk2/OpenCvDev/opencv/opencv_contrib-4.0.0/modules/hdf/include .
